#!/bin/sh

echo 'Creating APPLICANTS table in CDB'

sqlplus C\#\#MYUSER/mypassword@//localhost:1521/ORCLCDB  <<- EOF



  create table APPLICANTS (
                id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 42) NOT NULL PRIMARY KEY,
                GivenName VARCHAR(50),
                MiddleInitial VARCHAR(1),
                Surname VARCHAR(50),
                StreetAddress VARCHAR(100),
                City VARCHAR(100),
                State VARCHAR(2),
                ZipCode VARCHAR(5),
                County VARCHAR(50),
                EmailAddress VARCHAR(100),
                Birthday VARCHAR(12),
                NationalID VARCHAR(15),
                Occupation VARCHAR(200),
                create_ts timestamp DEFAULT CURRENT_TIMESTAMP,
                update_ts timestamp);

  CREATE OR REPLACE TRIGGER TRG_APPLICANTS_UPD
  BEFORE INSERT OR UPDATE ON APPLICANTS
  REFERENCING NEW AS NEW_ROW
    FOR EACH ROW
  BEGIN
    SELECT SYSDATE
          INTO :NEW_ROW.UPDATE_TS
          FROM DUAL;
  END;
  /

EOF

